server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    name: ds-user
    url: jdbc:mysql://localhost:3306/freeman_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: llw1123..
  jpa:
    show-sql: true
    open-in-view: true


logging:
  level:
    cn.liumouren.user: debug

