# 保护分支上的代码, 我们默认都是经过编译和测试
# 我们直接进行打包并部署
name: freeman-microservice
on:
  push:
    branches: [test]
  pull_request:
    branches: [test]
jobs:
  deploy-test:
    name: deploy-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # maven 缓存
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 打包
      - name: Package
        run: mvn clean package -U --settings settings.xml -Dmaven.test.skip=true -Dmaven.source.skip=true
      # 打包之后, 制作镜像, 上传 docker-registry
      - name: Upload Docker Registry
        run: |
          docker build -t uer:1.0.0 .
          docker login 115.159.210.143 -u admin -p llw1123
          docker push 115.159.210.143/freeman/uer:1.0.0