# 保护分支上的代码, 我们默认都是经过编译和测试
# 我们直接进行打包并部署
name: freeman-microservice
on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
jobs:
  deploy-beta:
    name: deploy-beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      # maven 缓存
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # 打包
      - name: Package
        run: mvn package
